#!/bin/bash

# Automagically deploy machines with libvirtd and debian preseed

DEBIAN_INSTALLER=http://ftp.debian.org/
DEBIAN_MIRROR_HOSTNAME=${DEBIAN_MIRROR_HOSTNAME:-ftp.debian.org}
LIBVIRT_DEFAULT_URI=${LIBVIRT_DEFAULT_URI:-qemu:///system}
LIBVIRT_NETWORK_ADDRESS=${LIBVIRT_NETWORK_ADDRESS:-192.168.122.1}
HTTP_PORT=${HTTP_PORT:-8080}

preseed_tar() {
  local name=$1
  mkdir -p "webroot/${name}/"
  tar cf "webroot/${name}/firstboot.tar" firstboot icvpn icvpn-meta -C machines/${name}/ $(find -L "machines/${name}/" -type f -printf "%P\n")
}

preseed_debian(){
  local name=$1
  mkdir -p "webroot/${name}/"
  cat debian_preseed.cfg |\
    sed -r "s/DEBIAN_MIRROR_HOSTNAME/${DEBIAN_MIRROR_HOSTNAME}/" |\
    sed -r "s/LIBVIRT_NETWORK_ADDRESS/${LIBVIRT_NETWORK_ADDRESS}/" |\
    sed -r "s/HOSTNAME/${name}/" |\
    sed -r "s/HTTP_PORT/${HTTP_PORT}/" \
    > "webroot/${name}/debian_preseed.cfg"
}

preseed_postinstall() {
  local name=$1
  mkdir -p "webroot/${name}/"
  cat postinstall |\
    sed -r "s/HOSTNAME/${name}/" |\
    sed -r "s/LIBVIRT_NETWORK_ADDRESS/${LIBVIRT_NETWORK_ADDRESS}/" |\
    sed -r "s/HTTP_PORT/${HTTP_PORT}/" \
    > "webroot/${name}/postinstall"
}

prefetch() {
  # http://ftp.debian.org/debian/dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
  mkdir -p cache/debian/dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64/
  wget -nv -c ${DEBIAN_INSTALLER}/debian/dists/wheezy/main/installer-amd64/current/images/MANIFEST -O cache/debian/dists/wheezy/main/installer-amd64/current/images/MANIFEST
  wget -nv -c ${DEBIAN_INSTALLER}/debian/dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz -O cache/debian/dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
  wget -nv -c ${DEBIAN_INSTALLER}/debian/dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux -O cache/debian/dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
  cp -r cache/* webroot/
}

build_vm() {
  local name=$1
  virt-install \
    --debug \
    --noautoconsole \
    --name=${name} \
    --ram=256 \
    --disk /var/lib/libvirt/images/${name}.img,size=2 \
    --location=http://${LIBVIRT_NETWORK_ADDRESS}:${HTTP_PORT}/debian/dists/wheezy/main/installer-amd64/ \
    --extra-args="\
      auto=true priority=critical vga=normal hostname=${HOSTNAME} \
      url=http://${LIBVIRT_NETWORK_ADDRESS}:${HTTP_PORT}/${name}/debian_preseed.cfg"
}

start_web(){
  rm -rfv webroot
  mkdir webroot
  pkill darkhttpd
  darkhttpd ./webroot --daemon --addr ${LIBVIRT_NETWORK_ADDRESS} --port ${HTTP_PORT} || exit 1
}

# Change directory and start local webserver
cd "$(dirname "$0")"

case $1 in
  -l)
    for machine in machines/*; do
      if [ -d $machine ]; then
        echo $(basename ${machine})
      fi
    done
    ;;
  -m)
    shift

    start_web
    prefetch

    while test $# -gt 0; do
      machine=$(basename $1)
      if [ -d machines/$machine ] ; then 
        preseed_tar $machine
        preseed_debian $machine
        preseed_postinstall $machine
        build_vm $machine
      fi
      shift
    done
    ;;
  *) 
    echo "Usage $0 [-l] [-m <machine> .. <machine>]"
esac
